name: Random Anime Notifications

on:
  workflow_dispatch:

jobs:
  loop-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Send random anime notifications in a loop
        run: |
          mkdir -p .

          TITLES=("Attack on Titan" "Naruto" "One Piece" "Jujutsu Kaisen" "Demon Slayer" "Bleach" "Death Note" "Dragon Ball Z" "Chainsaw Man")
          IMAGES=("https://cdn.myanimelist.net/images/anime/10/47347.jpg"
                  "https://cdn.myanimelist.net/images/anime/13/17405.jpg"
                  "https://cdn.myanimelist.net/images/anime/6/73245.jpg"
                  "https://cdn.myanimelist.net/images/anime/1633/122009.jpg"
                  "https://cdn.myanimelist.net/images/anime/1908/110405.jpg"
                  "https://cdn.myanimelist.net/images/anime/3/40451.jpg"
                  "https://cdn.myanimelist.net/images/anime/9/9453.jpg"
                  "https://cdn.myanimelist.net/images/anime/131/37705.jpg"
                  "https://cdn.myanimelist.net/images/anime/1806/126216.jpg")

          ICON="https://upload.wikimedia.org/wikipedia/commons/e/e3/Shingeki_no_Kyojin_logo.png"

          for i in {1..5}; do
            INDEX=$((RANDOM % ${#TITLES[@]}))
            TITLE=${TITLES[$INDEX]}
            IMAGE=${IMAGES[$INDEX]}

            echo "new Notification('$TITLE', {
              body: '$TITLE is the best anime!',
              icon: '$ICON',
              image: '$IMAGE'
            });" > notify.js

            git add notify.js
            git commit -m "Notify: $TITLE"
            git push

            echo "Sent notification: $TITLE"
            sleep 2
          done
          
